---
- name: test localhost command
  hosts: all
  
  tasks: 
    - name: check env
      debug:
        msg: 
        
    - name: hostname
      shell: "hostname"
      delegate_to: i-09719469ce4f38e83.ec2.internal
      become: yes
      
