---
- name: test localhost command
  hosts: all
  
  tasks: 
    - name: check env
      debug:
        var: hostvars[inventory_hostname]['tower_inventory_id']
        
    - name: hostname
      shell: "hostname"
      delegate_to: i-09719469ce4f38e83.ec2.internal
      become: yes
      
